from __future__ import annotations

import json

from .planner import DEFAULT_LLM_MODEL, SeriesPlan


def render_generator_code(
    plan: SeriesPlan,
    length: int = 168,
    freq: str = "h",
    start: str = "2026-07-01 00:00:00",
    seed: int | None = 42,
    model: str | None = None,
) -> str:
    plan_json = json.dumps(plan.to_dict(), ensure_ascii=False, indent=2)
    template = '''\
"""Replay script produced by generation_agent.

The script embeds the executable SeriesPlan and calls the package's main local
generation kernel, so frequency semantics, component workflow, multivariate
relationships, semantic validation, and future kernel fixes stay consistent with
the agent runtime.
"""

import json

from generation_agent.compact_storage import write_series_arrow
from generation_agent.agent import GenerationAgent
from generation_agent.planner import SeriesPlan


PLAN = SeriesPlan.from_dict(json.loads(r"""__PLAN_JSON__"""))


def generate(length=__LENGTH__, freq=__FREQ__, start=__START__, seed=__SEED__):
    return GenerationAgent(model=__MODEL__).generate_from_plan(
        PLAN,
        length=length,
        freq=freq,
        start=start,
        seed=seed,
    )


def write_arrow(df, path="generated_timeseries.arrow", freq=__FREQ__, start=__START__):
    final_plan = SeriesPlan.from_dict(df.attrs.get("final_plan", PLAN.to_dict()))
    metadata = {
        "description": final_plan.metadata.get("description", "generated by replay script"),
        "start": start,
        "frequency": freq,
        "length": int(len(df)),
        "seed": __SEED__,
        "domain": final_plan.domain,
        "unit": final_plan.unit,
        "generator_type": final_plan.generator_type,
        "semantic_type": final_plan.semantic_type,
        "validation_report": df.attrs.get("validation_report", {}),
        "component_workflow": df.attrs.get("component_workflow", {}),
        "component_report": df.attrs.get("component_report", {}),
        "storage_format": "arrow_ipc",
        "replay_script": True,
    }
    return write_series_arrow(df, path, metadata=metadata)


if __name__ == "__main__":
    frame = generate()
    write_arrow(frame)
    print(frame.head(12).to_string(index=False))
'''
    return (
        template.replace("__PLAN_JSON__", plan_json)
        .replace("__LENGTH__", str(int(length)))
        .replace("__FREQ__", repr(freq))
        .replace("__START__", repr(start))
        .replace("__SEED__", repr(seed))
        .replace("__MODEL__", repr(model or plan.metadata.get("model") or DEFAULT_LLM_MODEL))
    )
